name: Foo
description: Requesting Foo
title: "[Foo Request]: "
body:
  - type: input
    id: foo
    attributes:
      label: Foo for Fizz
      description: Foo Bar.
      placeholder: e.g. foo,bar
    validations:
      required: true
  - type: input
    id: fizz
    attributes:
      label: Fizz for Bazz
      description: Fizz Bazz.
      placeholder: e.g. Fizz, Bazz
    validations:
      required: true
  - type: input
    id: Bar
    attributes:
      label: Bar Foo
      description: Bar Foo
      placeholder: e.g. bar, foo
    validations:
      required: true
  - type: dropdown
    id: fooz
    attributes:
      label: Fooz
      description: Fooz?
      options:
        - Fizz
        - Bazz
        - Bar
        - Foo
    validations:
      required: true
  - type: dropdown
    id: Bazz
    attributes:
      label: Bazz
      description: Bazz
      options:
        - Bazz
        - Bar
        - Foo
        - Fizz
    validations:
      required: true
  - type: dropdown
    id: BuzzBazz
    attributes:
      label: FooBar
      options:
        - Buzz
        - Bazz
  - type: textarea
    id: Foooz
    attributes:
      label: FizzBozz
      description: BozzFazz
      placeholder: Fizz Bazz Fozz
    validations:
      required: true
