name: Fizz Bazz
on:
  issues:
    types:
      - labeled

jobs:
  fizz-fooz:
    if: ${{ github.event.label.name == 'onboard' }}
    name: Foo Faz
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: echo Foo
      - name: Get issues
        run: echo ${{ github.event.issue }}
